Apps/actual-server/docker-compose.yml
README.md

adding actual server

---

Apps/gladys/docker-compose.yml

Here is my working version of Gladys (tested on RPI4)

Gladys - Fix docker-compose.yml

---

Apps/immich/docker-compose.yml
Apps/playitgg/docker-compose.yaml
README.md

https://playit.gg is a tunnelling service for self hosted minecraft server. It allow you to publish it to the net without opening your ports and IP

add playitgg

---

Apps/homarr/docker-compose.yml
README.md

– Change image from `0.13.4` to` 0.14.2`
– Added `/homarr/data:/data` Volume
– Added `/data` Specific configuration

Update Homarr docker-compose.yml

---

Apps/immich/docker-compose.yml
README.md

⚠️ Next version will have breaking changes in docker-compose (v1.91).

update Immich to v1.90.2

---

Apps/dashdot/docker-compose.yml

Fixed a bug in dashdot that was preventing the app from displaying information about the used storage.

Update Dashdot docker-compose.yml

---

Apps/filebrowser/config.json
Apps/filebrowser/docker-compose.yml

The changes add the Filebrowser application to the BigBearCasaOS platform. Filebrowser is a reliable and performant file management, desktop sync, and file sharing tool. This change allows users to access their homeserver files from their browser.
The changes include:
- Adding the Filebrowser configuration in the `config.json` file, specifying the application's metadata.
- Adding the Filebrowser Docker Compose configuration, including volume mappings, environment variables, and port mapping.
- Updating the CasaOS-specific configuration, such as supported architectures, service information, and tips for users.

🐻 feat(filebrowser): Add Filebrowser to BigBearCasaOS

---

Apps/financial-freedom/docker-compose.yml

Updates the default email from name to "Financial Freedom" for a more
consistent and branded experience.

🔧 refactor(email): update default email from name

---

Apps/nextcloud/config.json
Apps/nextcloud/docker-compose.yml

Updates the nextcloud image used in the docker-compose file to a
custom version that includes the smbclient package. This allows the
nextcloud instance to access SMB shares, which is a requirement for
the organization's file storage needs.

🐻️ feat(nextcloud): Update nextcloud image to custom version

---

Apps/jellyseerr/config.json

Upgrades the Jellyseerr version from 1.9.2 to 2.0.1 in the
configuration file. This update brings new features and bug
fixes, improving the overall functionality and user experience.

✨ feat(jellyseerr): Upgrade Jellyseerr to version 2.0.1

---

Apps/wallos/docker-compose.yml

This change adds a "tips" section to the wallos docker-compose.yml file,
which includes a link to a community post with important information to
read before installing the wallos app.

✨ feat(wallos): add tips for before install

---

Apps/photoprism/config.json

Updates the PhotoPrism version in the config.json file from 231128 to
240420. This ensures the latest version of the PhotoPrism application
is used, which may include bug fixes, new features, or performance
improvements.

✨ feat: Update PhotoPrism version to 240420

---

Apps/photoprism/config.json
Apps/photoprism/docker-compose.yml

This pull request updates the PhotoPrism version from 240420 to 240915 in the `config.json` and `docker-compose.yml` files. The update includes bug fixes and improvements to the PhotoPrism application.
<###>🔖 feat(photoprism): update to version 240915
Updates the PhotoPrism version from 240420 to 240915 in the
config.json and docker-compose.yml files. This update includes
bug fixes and improvements to the PhotoPrism application.
- Incorporates the latest bug fixes and improvements to the PhotoPrism application
- Keeps the project up-to-date with the latest version of PhotoPrism

🔖 feat(photoprism): update to version 240915

---

Apps/phpmyadmin/config.json

This pull request updates the phpMyAdmin version from 5.2.1-fpm-alpine to 5.2.1. This change is made to ensure the latest stable version of phpMyAdmin is being used.

✨ feat(phpmyadmin): Update phpmyadmin version to 5.2.1

---

Apps/minio/docker-compose.yml

This pull request updates the container name and command for the Minio service.
The key changes include:
- Updating the container name to "big-bear-minio" for better descriptiveness
- Changing the command to use the array format so it works on CasaOS
These changes will help make the Minio service more easily identifiable and the command work in CasaOS.

✨ chore(minio): update container name and command

---

Apps/linkwarden/docker-compose.yml

This pull request updates the postgres image version from latest to 16 in the docker-compose.yml file for the linkwarden service. This ensures the application is using a specific and supported version of postgres.

✨ feat(linkwarden): update postgres image to 16

---

Apps/eufy-security-ws/docker-compose.yml

This pull request adds a new `tips` section to the `eufy-security-ws` service in the docker-compose file. The new section includes a link to a community post with important information that users should read before installing the service. This change aims to provide better guidance and instructions for users setting up the `eufy-security-ws` service.

✨ feat(eufy-security-ws): Add installation tips to docker-compose

---

Apps/Homepage/config.json

This pull request updates the homepage version to v0.9.13 to include the latest bug fixes and improvements.

✨ feat(homepage): Bump homepage version to v0.9.13

---

Apps/ollama-amd/config.json

This pull request updates the version of the `ollama-amd` app to `0.4.4-rocm`. This change is necessary to ensure the app is up-to-date and includes the latest features and bug fixes.

✨ feat(ollama-amd): Bump version to 0.4.4-rocm

---

Apps/kavita/config.json

This pull request updates the Kavita version in the `config.json` file from `0.8.3` to `0.8.4`. This change is to ensure the application is running the latest stable version.
<###>✨ feat: Bump Kavita version to 0.8.4
Updates the Kavita version in the config.json file from 0.8.3 to
0.8.4. This change is to ensure the application is running the
latest stable version.
<###>
- Keeps the application up-to-date with the latest stable version of Kavita
- Ensures the application benefits from the latest bug fixes and improvements

✨ feat: Bump Kavita version to 0.8.4

---

Apps/big-bear-casaos-user-management/docker-compose.yml

**PR Description:**
This pull request introduces a rebranding of the CasaOS User Management Service to BigBearCasaOS User Management Service. The changes are made in the `docker-compose.yml` file to reflect the new branding.

✨ feat(user-management): Rebrand CasaOS to BigBearCasaOS

---

Apps/upsnap/config.json
Apps/upsnap/docker-compose.yml

This pull request adds the configuration files for the Upsnap application, including the `config.json` and `docker-compose.yml` files. This allows the Upsnap application to be easily deployed and managed within the BigBearCasaOS platform.
The Upsnap application is a simple wake on LAN web app written with SvelteKit, Go, and PocketBase. This integration provides users with an easy way to set up and manage the Upsnap application within their BigBearCasaOS environment.

✨ feat(upsnap): Add Upsnap application configuration

---

Apps/umbrel-os/docker-compose.yml

This pull request updates the installation instructions for Umbrel OS in the `docker-compose.yml` file. The new instructions provide a link to a community discussion about adding Umbrel OS to BigBearCasaOS.
- Updated the Umbrel OS installation instructions in the `docker-compose.yml` file to include a link to the community discussion.
The goal of this change is to provide users with more up-to-date and helpful information about installing Umbrel OS on BigBearCasaOS.

✨ feat(umbrel-os): Update installation instructions

---

Apps/playit-docker-web/docker-compose.yml

This pull request updates the main service name in the `docker-compose.yml` file from `big-bear-cloudflared-web` to `big-bear-playit-docker-web`. This change reflects the correct service name for the Playit.gg application.
<###>✨ feat(docker-compose): update main service name
Updates the main service name in the docker-compose.yml file
from `big-bear-cloudflared-web` to `big-bear-playit-docker-web`.
This change reflects the correct service name for the Playit.gg
application.

✨ feat(docker-compose): update main service name

---

recommend-list.json

This pull request adds a new app, "big-bear-casaos-user-management", to the recommendation list in the "recommend-list.json" file. This change will allow the app to be recommended to users in the CasaOS platform.
The commit message for this change is:
<###>✨ feat: Add new app to recommendation list
Adds the "big-bear-casaos-user-management" app to the
recommendation list in the "recommend-list.json" file.
This change will allow the app to be recommended to
users in the CasaOS platform.
<###>

✨ feat: Add new app to recommendation list

---

Apps/coolify/config.json
Apps/coolify/docker-compose.yml

This pull request updates the Coolify Docker image and configuration to version 4.0.0-beta.380. This update includes bug fixes and improvements to the Coolify application.
<###>🔖 feat(coolify): Update Coolify to version 4.0.0-beta.380
Updates the Coolify Docker image and configuration to version 4.0.0-beta.380.
This update includes bug fixes and improvements to the Coolify application.
<###>

🔖 feat(coolify): Update Coolify to version 4.0.0-beta.380

---

Apps/budibase/config.json

This pull request updates the Budibase version in the `config.json` file from `3.2.29` to `3.2.32`. This change is necessary to ensure the application is running the latest stable version of the Budibase platform.

🔖 feat(version): Bump Budibase version to 3.2.32

---

Apps/ollama-amd/config.json
Apps/ollama-cpu/config.json
Apps/ollama-nvidia/config.json

This pull request bumps the version of the Ollama apps to 0.5.5 for NVIDIA, AMD, and CPU configurations. The update includes bug fixes and performance improvements to ensure the apps are running smoothly across different hardware setups.

✨ feat: Bump Ollama app versions to 0.5.5

---

Apps/budibase/config.json
Apps/lobe-chat/config.json
Apps/phpmyadmin/config.json

**✨ feat: Update app versions**
This pull request updates the versions for the following apps:
- Budibase: 3.3.3 -> 3.3.5
- Lobe Chat: 1.49.4 -> v1.49.6
- phpMyAdmin: 5.2.1 -> 5.2.2
These updates ensure the apps are running the latest stable versions.

✨ feat: Update app versions

---

templates/README.md

The changes in this pull request update the description of the BigBearCasaOS App Store in the README.md file. The new description provides more details about the app store's relationship with IceWhale and its status as an independent community-maintained app store that is pre-installed on IceWhale's hardware and software platforms.

✨ docs(README): update app store description

---

Apps/calcom/config.json

This pull request updates the Cal.com version in the `config.json` file from `4.9.11` to `4.9.12`. This change is necessary to ensure the application is running the latest stable version of the software.
🔖 feat(config): update Cal.com version to 4.9.12
Updates the Cal.com version in the config.json file from 4.9.11 to
4.9.12. This change is necessary to ensure the application is running
the latest stable version of the software.
- Ensures the application is using the latest stable version of Cal.com
- Provides bug fixes and improvements included in the 4.9.12 release
No known risks. This is a minor version update.

🔖 feat(config): update Cal.com version to 4.9.12

---

Apps/dozzle/config.json

This pull request updates the Dozzle container image version from 8.11.5 to 8.11.6. The update includes bug fixes and improvements to the Dozzle application.
<###>✨ feat(dozzle): update to version 8.11.6
Updates the Dozzle container image version from 8.11.5 to 8.11.6.
This update includes bug fixes and improvements to the Dozzle
application.
<###>
- Applies the latest bug fixes and improvements to the Dozzle application
- Keeps the Dozzle deployment up-to-date with the latest version

✨ feat(dozzle): update to version 8.11.6

---

Apps/nextcloud/config.json
Apps/nextcloud/docker-compose.yml

This pull request upgrades the Nextcloud Docker image from version 0.0.5 to 0.0.6. The update includes bug fixes and improvements to the Nextcloud application. The `config.json` file has also been updated to reflect the new image version.
<###>🔖 feat(nextcloud): Upgrade Nextcloud image to version 0.0.6
Upgrades the Nextcloud Docker image from version 0.0.5 to 0.0.6. This update includes bug fixes and improvements to the Nextcloud application. The config.json file is also updated to reflect the new image version.
- Improved stability and performance of the Nextcloud application
- Bug fixes and enhancements included in the new image version
- Keeping the application up-to-date with the latest improvements
No significant risks are expected with this upgrade. The changes are limited to the …

🔖 feat(nextcloud): Upgrade Nextcloud image to version 0.0.6

---

Apps/bookstack/config.json
Apps/bookstack/docker-compose.yml

This pull request updates the BookStack application to the latest version 25.02.20250226. The update includes bug fixes and improvements to the application.

🔖 feat(bookstack): update to latest version

---

Apps/authentik/config.json
Apps/authentik/docker-compose.yml

This pull request updates the authentik server and worker containers to version 2025.2.1. The update includes bug fixes and improvements to the authentik authentication platform.
🔖 feat(authentik): update authentik to version 2025.2.1
Updates the authentik server and worker containers to version 2025.2.1. This update includes bug fixes and improvements to the authentik authentication platform.

🔖 feat(authentik): update authentik to version 2025.2.1

---

Apps/invoice-ninja/config.json

This pull request updates the Invoice Ninja version in the `config.json` file from `5.11.52` to `5.11.53`. This change is necessary to ensure the application is running the latest stable version.
- Updated the `invoice-ninja` version in the `config.json` file to `5.11.53`.

🔖 feat(config): update invoice-ninja version to 5.11.53

---

Apps/cloudflared-web/config.json

This pull request adds a YouTube link to the configuration of the `cloudflared-web` app. The new link will allow users to access a video tutorial or other relevant content directly from the app, providing them with additional resources and guidance.
The changes include:
- Adding a new configuration option to store the YouTube link
- Updating the app's UI to display the YouTube link and provide a way for users to access it
These improvements will enhance the user experience and make it easier for users to find helpful information about the `cloudflared-web` app.

✨ feat(cloudflared-web): Add YouTube link to config

---

templates/README.md

This pull request adds a new video tutorial link to the README file, providing users with a visual guide on how to use the UI. The goal of this change is to enhance the documentation and make it more accessible for users.
The commit message for this change is:
<###>📽️ feat: Add video tutorial link to README
Adds a new video tutorial link to the README file to provide users with
a visual guide on how to use the UI. This change aims to enhance the
documentation and make it more accessible for users.
<###>

📽️ feat: Add video tutorial link to README

---

Apps/btop/config.json
Apps/btop/docker-compose.yml

✨ feat(btop): add authentication to GOTTY and update btop version
This pull request includes the following changes:
1. Adds environment variables for GOTTY authentication (user, password, and enabled) to the btop container.
2. Updates the btop version to 0.0.9 in the docker-compose.yml and config.json files.
These changes improve the security of the btop container by requiring authentication to access the GOTTY web interface. The updated btop version likely includes bug fixes or new features that improve the overall functionality of the application.

✨ feat(btop): add authentication to GOTTY and update btop version

---

Apps/MaybeFinance/config.json
Apps/MaybeFinance/docker-compose.yml
README.md

Reverts bigbeartechworld/big-bear-casaos#3584

Revert "update: MaybeFinance to v0.5.0 stable"

---

Apps/big-bear-casaos-user-management/docker-compose.yml

- Updated the thumbnail and screenshot paths in the documentation for the Big Bear CasaOS User Management feature.

📝 docs(big-bear-casaos-user-management): update thumbnail and screenshot paths

---

Apps/plex-nvidia/config.json
Apps/plex-nvidia/docker-compose.yml

- Added a new application for Plex with NVIDIA GPU support
- Includes configuration files, environment variables, and volume mounts to run Plex with NVIDIA GPU acceleration
- Allows users to stream movies and TV shows with improved performance on systems with NVIDIA GPUs

🐻 feat(plex-nvidia): Add Plex with NVIDIA GPU support

---

Apps/send-visee/docker-compose.yml

- Update environment variables to reflect the current application configuration
- Update the container path for file storage
- Update the container port to 1443

✨ feat(send-visee): update docker-compose configuration

---

Apps/passwordpusher/config.json
Apps/passwordpusher/docker-compose.yml

- Added installation instructions with a link to a community post in docker-compose.yml to assist users before installing passwordpusher.  
- Updated config.json to include a YouTube tutorial link for improved user support and onboarding.

✨ docs: add install tips and YouTube link for passwordpusher

---

Apps/pihole-updatelists/config.json
Apps/pihole-updatelists/docker-compose.yml

- Added a complete docker-compose.yml for the big-bear-pihole-updatelists service with environment variables, volume mounts, port mappings, and network settings.
- Integrated CasaOS-specific configuration for architecture support, metadata, and UI integration.
- Added a config.json file defining app metadata including id, version, and image for deployment and management.
- Enabled easy deployment and management of the Pi-hole fork with updated blocklist and regex list capabilities.

✨ feat: add pihole-updatelists docker-compose config

---

Apps/btop/config.json
Apps/btop/docker-compose.yml

- Upgrade btop to version 0.1.2
- Update version number in config.json and docker-compose.yml files
- Ensure application is running the latest stable version
- Take advantage of any bug fixes or new features

feat(btop): Upgrade btop to version 0.1.2

---

Apps/gitea-mirror/config.json
Apps/gitea-mirror/docker-compose.yml

- Update the `docs_link` in the `config.json` file to point to the community documentation for the Gitea Mirror application
- Update the `author` field in the `docker-compose.yml` file to use double quotes for consistency
- Add initial version, author, and description information to the `docker-compose.yml` file
- Improve the health check configuration in the `docker-compose.yml` file for better reliability
- Update the `tips` section in the `docker-compose.yml` file to provide a link to the community documentation instead of detailed instructions

🔧 feat(gitea-mirror): Update configuration and documentation

---

Apps/Homepage/docker-compose.yml

- Updated the developer for the Homepage application from "ajnart" to "gethomepage" to reflect the actual developer
- Updated the icon URL for the Homepage application to a more appropriate one

🔧 feat(homepage): Update developer and icon

---

Apps/actual-server/docker-compose.yml

- Updates the icon for the Actual Budget application in the docker-compose.yml file
- The new icon is sourced from a different location to provide a more appropriate visual representation of the application

🎨 feat(actual-budget): Update application icon

---

Apps/changedetection/docker-compose.yml

- Updates the icon URL for the changedetection application in the docker-compose.yml file
- The new icon URL points to a more appropriate and consistent icon source

🔧 feat(changedetection): Update icon URL

---

Apps/stalwart-mail/docker-compose.yml

- Updated the icon for the stalwart-mail app in the docker-compose.yml file
- The new icon is more generic and represents the Stalwart brand better

🔧 feat(docker-compose): update stalwart-mail icon

---

Apps/rocket-chat/docker-compose.yml

- Updates the icon URL for the Rocket.Chat application in the docker-compose.yml file
- The new icon URL points to a more appropriate and up-to-date source for the Rocket.Chat logo

🔧 feat(rocket-chat): Update Rocket.Chat icon URL

---

Apps/tandoor/docker-compose.yml

- Updates the icon URL for the Tandoor Recipes application in the docker-compose.yml file
- The new icon URL points to a more appropriate icon for the application

🔧 feat(tandoor): update icon URL

---

Apps/pocketid/docker-compose.yml

- Updated the installation tips for Pocket ID to provide a link to the community documentation, which contains more detailed and up-to-date information about the installation process.

✨ feat: Improve Pocket ID installation instructions

---

Apps/wishlist/docker-compose.yml

- Updated the installation instructions for the Wishlist app to reflect the new community thread URL.

🔖 docs(wishlist): update installation instructions

---

Apps/zipline/config.json
Apps/zipline/docker-compose.yml

- Updates the Zipline container image from 4.1.0 to 3.7.13
- Addresses a compatibility issue with a downstream dependency introduced in the 4.1.0 release

⚙️ feat(zipline): Update Zipline container image to 3.7.13

---

Apps/wishlist/config.json

- Updates the config.json file to use the id 'wishlist' instead of 'big-bear-wishlist'
- Aligns the config with the app's current naming convention

🔧 refactor(wishlist): update config id to 'wishlist'

---

Apps/MaybeFinance/config.json
Apps/MaybeFinance/docker-compose.yml

- Updated MaybeFinance to latest version (sha-347c0a790693031fdd3b32792b5b6792693d1805)
- Added Redis service for caching and job queue functionality
- Added arm64 architecture support

feat(MaybeFinance): update to latest version and add Redis support

---

Apps/dockpeek/config.json
Apps/dockpeek/docker-compose.yml

- Add dockpeek v1.5.5 - a lightweight, self-hosted Docker dashboard
- Provides quick access to running containers and exposed ports
- Includes one-click access to containerized web apps
- Multi-host Docker management
- Automatic container detection
- Image update checking
- Configurable authentication (SECRET_KEY, USERNAME, PASSWORD)
- Supports amd64 and arm64 architectures

feat: add dockpeek docker dashboard app
