bigbeartechworld/big-bear-casaos

Apps/gluetun/docker-compose.yml
Change the name from Glutun to the correct docker name "Gluetun" on the CasaOS store data.
=> Fix Gluetun name on the CasaOS store

Apps/immich/docker-compose.yml, README.md
> [!NOTE] 
> **The next release will have a different `docker-compose` file :**
> This release is the final version where we bid farewell to the `immich-web` and `immich-proxy` containers. Starting in the next release, the two containers will be consolidated into the `immich-server` container for easier deployment and maintenance.
=> update Immich to v1.87.0

Apps/dashdot/docker-compose.yml
The current image supports arm64, but the docker file is not set for this.
=> Update docker-compose.yml to support arm64

Apps/ghostfolio/docker-compose.yml
I noticed that the configuration for redis is not correct which results in problems in the functioning of the application by not connecting to the redis server
=> Ghostfolio - fix redis host name in docker-compose.yml

Apps/obsidian/config.json, Apps/obsidian/docker-compose.yml
Adds the Obsidian note-taking app configuration to the Big Bear CasaOS platform. The changes include:
- Add `config.json` file with application metadata
- Add `docker-compose.yml` file with service definition and CasaOS-specific configuration
- Provide detailed descriptions, tags, and other metadata to enhance the app's presentation in the CasaOS platform
=> ✨🐻 feat(obsidian): Add Obsidian note-taking app configuration

Apps/owncloud/config.json, Apps/owncloud/docker-compose.yml
This commit adds the necessary configuration to set up an Owncloud instance using Docker Compose. The key changes include:
- Defines the `big-bear-owncloud` service with the Owncloud server image and necessary environment variables.
- Mounts the local `/DATA/AppData/$AppID/data` directory to the container's `/mnt/data` for persistent storage.
- Maps port 8080 of the host to port 8080 of the container.
- Configures the `big-bear-owncloud-db` service with a MariaDB database and necessary environment variables.
- Mounts the `/DATA/AppData/$AppID/data/mysql` directory to the container's `/var/lib/mysql` for persistent database storage.
- Adds the `big-bear-owncloud-redis` service for the Owncloud Redis cache.
- Includes CasaOS-specific configuration for environment variables, volumes, and …
=> 🔨 feat(owncloud): Add Owncloud docker-compose setup

Apps/syncthing/config.json, Apps/syncthing/docker-compose.yml
Adds the configuration files for the Syncthing application, including the
`config.json` and `docker-compose.yml` files. Syncthing is a peer-to-peer
file synchronization tool that allows users to keep their files
synchronized across multiple devices. This change adds the necessary
configuration to run Syncthing as a CasaOS application.
=> 🎉 feat(syncthing): add syncthing application configuration

Apps/scrutiny/config.json, Apps/scrutiny/docker-compose.yml
The changes made in this commit add a Docker Compose configuration file and metadata for the Scrutiny application. The key changes are:
- Added a Docker Compose file `docker-compose.yml` that defines the Scrutiny service, including image, volumes, ports, and CasaOS-specific configuration.
- Added a `config.json` file with metadata about the Scrutiny application, such as the image, version, and links to related resources.
These changes will allow the Scrutiny application to be easily deployed and integrated into the CasaOS platform, providing users with a way to monitor the health of their server's hard drives.
=> 🚀 feat(scrutiny): add Docker Compose configuration and metadata

Apps/linkstack/config.json
Adds a YouTube link to the `linkstack` app's configuration.
This allows users to access a video demonstration of the app.
=> ✨ feat(linkstack): add YouTube link to config

Apps/paperless-ngx/config.json, Apps/paperless-ngx/docker-compose.yml
This commit introduces the following changes to the paperless-ngx docker-compose setup:
- Adds CasaOS-specific configuration, including environment variables and volume mounts
- Updates the environment variables for the paperless-ngx service to include necessary configuration for the application
- Configures the Redis broker and PostgreSQL database services
The changes aim to provide a comprehensive setup for deploying the paperless-ngx application within a CasaOS environment, ensuring seamless integration and ease of deployment.
🔨 feat(paperless-ngx): add documentation tips for installation
The changes add a new `tips` section to the `paperless-ngx` service in the
`docker-compose.yml` file. This section includes a `before_install` tip
with a link to community documentation that users …
=> ⚗️ feat(paperless-ngx): configure CasaOS integration and update environment variables

Apps/reactive-resume/docker-compose.yml
- Updates the Minio container to the latest version (RELEASE.2024-09-13T20-26-02Z-cpuv1)
- Renames the Postgres container from `big-bear-reactive-resume-postgres` to `big-bear-reactive-resume-db`
- These changes ensure the application is using the latest versions of the supporting services, and improve the clarity of the container names.
=> ♻️ chore(docker): update Minio and Postgres containers

Apps/tududi/docker-compose.yml
Removes the arm64 architecture support from the tududi
application's docker-compose configuration. This change is made
to simplify the deployment process and reduce the maintenance
overhead, as the arm64 architecture is not a primary target for
this application.
=> 🐳 feat(tududi): remove arm64 architecture support

Apps/nextcloud-with-smbclient/config.json, Apps/nextcloud-with-smbclient/docker-compose.yml
This commit introduces a new Docker Compose configuration for a Nextcloud
setup with an SMB client. The key changes include:
- Defines the `big-bear-nextcloud-smb` application with a container for the
Nextcloud app, a PostgreSQL database, and a Redis cache.
- Configures the Nextcloud app container with environment variables for the
database, Redis, and other settings.
- Mounts the Nextcloud data directory on the host to persist data.
- Includes healthchecks for the database and Redis services to ensure
they are running correctly.
- Provides CasaOS-specific configuration, including container paths and
environment variable descriptions.
=> ✨ feat: Add Nextcloud with SMB client setup

Apps/viseron/docker-compose.yml
This pull request renames the `PUID` and `PGID` environment variable keys to `container` in the docker-compose configuration. This change improves the readability and maintainability of the docker-compose configuration by using more semantically meaningful variable names.
=> 🐳 feat(docker-compose): rename environment variable keys

Apps/wallos/config.json, Apps/wallos/docker-compose.yml
This commit adds the necessary configuration files for the Wallos application to be
deployed using Docker Compose. The key changes include:
- Adding the `docker-compose.yml` file that defines the Wallos service and its
associated environment variables, volumes, and port mappings.
- Adding the `config.json` file that provides metadata about the Wallos
application, such as the version, image, and links to documentation and
YouTube videos.
These changes will make it easier to set up and deploy the Wallos application
in a containerized environment, such as CasaOS.
=> 🐳 feat(wallos): Add docker-compose and config.json for Wallos

Apps/photoprism/docker-compose.yml
- Update the PhotoPrism Docker image to the latest version (240420)
- Modify the JPEG quality setting to be a string instead of an integer
- Increase the `PHOTOPRISM_ORIGINALS_LIMIT` to 5000
- Optimize the MariaDB container command by using an array format
These changes improve the overall performance and configuration of the PhotoPrism application, ensuring better image processing and storage capabilities.
=> 🚀 feat(photoprism): update image tag and optimize configuration

Apps/bookstack/docker-compose.yml
This pull request introduces the following changes:
1. Updates the MariaDB data volume mount path from `/var/lib/mysql` to `/config` in the BookStack Docker Compose configuration. This change aligns the volume mount path with the recommended best practices for container-based applications, where the `/config` directory is typically used to store persistent application data.
2. Adds a new environment variable `APP_KEY` to the BookStack service, which is required for the application to function correctly. This environment variable is set to a base64-encoded value, which should be replaced with a unique value for the specific deployment.
These changes will improve the overall configuration and deployment of the BookStack application.
=> ✨ feat(bookstack): Update MariaDB data volume mount path

Apps/coolify/docker-compose.yml
Updates the healthcheck retries from string to integer for various services
in the docker-compose file. This ensures that the healthcheck retries are
properly parsed and handled by the Docker Compose engine.
=> 🔧 fix(docker-compose): update healthcheck retries

Apps/phpmyadmin/docker-compose.yml
The changes update the phpmyadmin docker image from the fpm-alpine
variant to the standard variant. This is done to simplify the
configuration and reduce the complexity of the deployment.
=> ✨ feat(phpmyadmin): update phpmyadmin docker image to 5.2.1

Apps/playit-docker-web/docker-compose.yml
- Update the installation instructions for the Playit Docker Web application in the BigBearCasaOS community guide
- The new link points to the correct thread for the Playit Docker Web application
The current installation instructions were outdated and pointed to an incorrect thread. This update ensures the documentation provides the correct information for users setting up the Playit Docker Web application.
=> 🔖 docs(playit-docker-web): update installation instructions

Apps/nextcloud-with-smbclient/docker-compose.yml
This pull request updates the title and description of the "Nextcloud with SMB" app to indicate that it is a legacy version and users should use the BigBearCasaOS Nextcloud app instead.
The changes include:
<###>
- Update the app title and description to indicate that this is a legacy version and users should use the BigBearCasaOS Nextcloud app instead.
<###>
This change helps to provide clear guidance to users and ensures they are directed to the recommended Nextcloud app.
=> 🔖 feat(nextcloud-with-smbclient): update app title and description

Apps/jlesage-firefox/config.json, Apps/jlesage-firefox/docker-compose.yml
This pull request adds a new CasaOS application for the Jlesage Firefox browser container. The changes include:
- Added a `docker-compose.yml` file to define the Firefox container service
- Configured the container with a VNC password and a default launch URL
- Provided CasaOS-specific metadata, including supported architectures, description, and installation tips
- Added a `config.json` file with basic application information
The goal of these changes is to provide a convenient way for CasaOS users to access the Firefox browser through a web-based interface, without the need for local installation or configuration.
=> ✨ feat(jlesage-firefox): add Firefox browser container

Apps/lyrionmusicserver/docker-compose.yml
This pull request updates the icon URL for the `lyrionmusicserver` application in the `docker-compose.yml` file. The new URL points to the `logo.png` file in the `big-bear-casaos` repository instead of the previous location.
<###>🔧 feat(docker-compose): Update lyrionmusicserver icon URL
Updates the icon URL for the lyrionmusicserver application in the
docker-compose.yml file. The new URL points to the logo.png file in the
big-bear-casaos repository instead of the previous location.
<###>
The previous icon URL was outdated, and this change ensures that the correct logo is displayed for the `lyrionmusicserver` application.
=> 🔧 feat(docker-compose): Update lyrionmusicserver icon URL

Apps/MaybeFinance/docker-compose.yml
This pull request updates the PostgreSQL database host and port mapping for the MaybeFinance application in the Docker Compose configuration.
The key changes include:
- Updating the `DB_HOST` environment variable to use a more descriptive name for the PostgreSQL database service.
- Changing the port mapping from host port 3000 to host port 4000, while keeping the container port at 3000.
- Updating the `port_map` value in the CasaOS configuration to reflect the new host port.
These changes are made to improve the clarity and maintainability of the Docker Compose configuration for the MaybeFinance application.
=> ✨🐻 feat(maybe-finance): Update PostgreSQL database host and port mapping

Apps/morphos/docker-compose.yml
This pull request updates the temporary storage volume mount path for the morphos container in the Docker Compose configuration. The changes include:
- Using a dynamic `$AppID` variable instead of a hardcoded path for the temporary storage volume mount.
- This allows for better organization and separation of data for different applications.
The changes are described in the commit message:
> 🐳 feat(docker-compose): update tmp volume mount path
>
> Updates the temporary storage volume mount path for the
> morphos container to use a dynamic $AppID variable instead
> of a hardcoded path. This allows for better organization and
> separation of data for different applications.
=> 🐳 feat(docker-compose): update tmp volume mount path

Apps/big-bear-casaos-user-management/config.json, Apps/big-bear-casaos-user-management/docker-compose.yml
This pull request bumps the version of the `big-bear-casaos-user-management` app from `0.0.1` to `0.1.0`. The update includes bug fixes and improvements to the user management functionality.
- Bumped the version to `0.1.0` in the codebase
=> 🔖 feat(user-management): Bump version to 0.1.0

Apps/viseron/config.json, Apps/viseron/docker-compose.yml
This pull request upgrades the Viseron container to version 3.0.0 and updates the container paths to better align with the new version's structure. The key changes are:
- Upgrade the container image to `roflcoopter/viseron:3.0.0`
- Change the container path for recordings to `/segments`, `/snapshots`, `/thumbnails`, and `/event_clips`
- Remove the mapping for `/var/run/docker.sock` as it is no longer required
- Add `shm_size` configuration to increase the shared memory size
- Update the environment variables to include `PUID` and `PGID`
=> ✨ feat(viseron): Upgrade to version 3.0.0 and update container paths

Apps/poste-io/docker-compose.yml, Apps/stalwart-mail/docker-compose.yml
- Updated developer information in app metadata for "Stalwart Mail Server" and "Poste.io" apps
- "Stalwart Mail Server" app is now attributed to "stalwartlabs" instead of "bigbeartechworld"
- "Poste.io" app is now attributed to "analogic" instead of "bigbeartechworld"
=> 🔧 refactor: Update developer information in app metadata

recommend-list.json
- Removed the `big-bear-casaos-user-management` app from the recommendation list as it is no longer needed or relevant.
=> 🔥 feat: remove app from recommendation list

Apps/immich-without-machine-learning/docker-compose.yml, Apps/immich/docker-compose.yml, renovate.json
- Downgraded the Postgres image used in the Immich application's Docker Compose configuration from version 16 to version 14 to address compatibility issues.
- Disabled Renovate updates for the `ghcr.io/immich-app/postgres` Docker image to prevent unintended updates to the Postgres version, which could potentially break the application.
=> Immich downgrade postgres image to 14

Apps/obsidian-livesync/docker-compose.yml
- Adds a new line in the docker-compose.yml file to include a link to a video tutorial for the Obsidian LiveSync setup
- Provides users with an additional resource to help them configure the service
=> ✨ feat(obsidian-livesync): add video tutorial link to docker-compose

Apps/portainer-agent/docker-compose.yml, Apps/portainer/docker-compose.yml
- Update icon URLs for Portainer and Portainer Agent applications in `docker-compose.yml` files
- New icon URLs point to a different source at `https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer.png`, which likely provides a more suitable or updated icon
=> 🔧 feat(portainer): update icon URLs

Apps/romm/config.json, Apps/romm/docker-compose.yml
• Update Romm Docker image from version 3.10.3 to 4.0.0
• Add support for new metadata providers: ScreenScraper, RetroAchievements, and Hasheous API
• Include CasaOS environment variable descriptions for all new API configuration options
=> feat(romm): update to version 4.0.0 with enhanced metadata provider support

Apps/upsnap/config.json
• Fixed version mismatch between config.json (5.1.8) and docker-compose.yml (5.1.9)
• Updated config.json version to 5.1.9 to match docker-compose.yml
=> fix: update upsnap version to 5.1.9 in config.json

Apps/stalwart-mail/config.json, Apps/stalwart-mail/docker-compose.yml
- Changed to latest
- Changed to new image - stalwart, not mail-server, as said in installation guide on stalwart:
```
$ docker pull stalwartlabs/stalwart:lates
```
[Source](https://stalw.art/docs/install/platform/docker)
The [stalwartlabs/mail-server](https://hub.docker.com/r/stalwartlabs/mail-server) is archived.
=> Fix Stalwart Mail

Apps/stalwart-mail/docker-compose.yml
The volume mapping is wrong, so after redeploying the container the data is gone.
=> Fixed Stalwart volume mapping

Apps/immich-aio-alpine/config.json, Apps/immich-aio-alpine/docker-compose.yml, Apps/immich-without-machine-learning/config.json, Apps/immich-without-machine-learning/docker-compose.yml, Apps/immich/config.json, Apps/immich/docker-compose.yml
- Bump app manifest version 1.143.1 to 20.0.
- Pin immich-server image to ghcr.io/immich-app/immich-server:v2.0.0 in both docker-compose files.
- Reformat docker-compose files by expanding inline comments into dedicated commented blocks (ports, volumes, environment, depends_on, x-casaos) for clarity.
- Add and align CasaOS metadata comments (architectures, description, tagline) and ensure x-casaos env mappings are present where needed.
- Preserve database and redis service settings; add explicit comment for optional DB_STORAGE_TYPE and keep postgres image/version unchanged.
=> ✨ feat: bump Immich to v2.0.0 and tidy compose configs

Apps/immich-aio-alpine/config.json, Apps/immich-aio-alpine/docker-compose.yml, Apps/immich-without-machine-learning/config.json, Apps/immich-without-machine-learning/docker-compose.yml, Apps/immich/config.json, Apps/immich/docker-compose.yml
Update Docker Compose and app metadata to use Immich v2.0.0
images and corresponding alpine image tag. This changes the server
and machine-learning container images from v1.143.1 to v2.0.0, and
updates the imagegenius immich alpine build from 1.131.3-alpine to
2.0.0-alpine. Also update config.json version fields to reflect the
new image tags.
Reason: bring deployments up to the new major Immich release to pick
up features, fixes, and compatibility improvements. Ensure config
metadata matches the deployed image versions.
- Bump server container image from v1.143.1 to v2.0.0
- Bump machine-learning container image from v1.143.1 to v2.0.0
- Update imagegenius immich alpine build from 1.131.3-alpine to 2.0.0-alpine
- Update config.json version fields to reflect new image tags
=> ✨ bump(immich): upgrade Immich images to v2.0.0
